### PR TITLE
Complete result.java

### PR DESCRIPTION
**Pull request by Csedge**

### CODE REVIEW

**Comment by Aqcurate** [comment]
Looks good. Maybe format the code with standard conventions. Spaces between equals. camelCase for private vars.

**Comment by Csedge** [comment]
I fined it now

**Review by Aqcurate — APPROVED** [review]
Looks good.

**Review by staslyakhov — APPROVED** [review]
Looks good to me as well.

**Comment by KSARK** [comment]
#11

**Pull request merged**
