### PR TITLE
Implement status bars

### PR DESCRIPTION
**Pull request by KSARK**
See #29

### CODE REVIEW

**Comment by Csedge** [comment]
That's good, but can you merge the css from the dev branch with yours? and try to intergrate with the lastest dev to check if it was working correctly because you are development it with the old version.

**Comment by Aqcurate** [comment]
I fixed a rendering bug and changed the attack status bar location to make everything more clear.

**Review by Aqcurate — APPROVED** [review]
Looks good to me now!

**Comment by Aqcurate** [comment]
We might want to fix the bottom status bar scaling issues. But that can be deferred for now.

**Review by staslyakhov — APPROVED** [review]
Status bars look good

**Pull request merged**
