### PR TITLE
Add the button's style

### PR DESCRIPTION
**Pull request by Csedge**
Add the button's style

### CODE REVIEW

**Comment by Aqcurate** [comment]
You've included a few too many files. 

Everything in out/ should not be committed.

Also, why are we hardcoding \&nbsp;? This should be done purely using CSS.

**Comment by Csedge** [comment]
> You've included a few too many files.
> 
> Everything in out/ should not be committed.
> 
> Also, why are we hardcoding &nbsp;? This should be done purely using CSS.

OK I remove it

**Comment by Aqcurate** [comment]
We should also not inline style.

**Comment by Aqcurate** [comment]
Resolved the conflicts. Good to merge?

**Review by Aqcurate — APPROVED** [review]
Looks alright to me.

**Review by KSARK — APPROVED** [review]
Looks good

**Review by staslyakhov — APPROVED** [review]
Button styles look good.

**Pull request merged**
